/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MoreRouteImport } from './routes/more'
import { Route as ManageRouteImport } from './routes/manage'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomersIndexRouteImport } from './routes/customers.index'
import { Route as CourtsIndexRouteImport } from './routes/courts.index'
import { Route as BookingsIndexRouteImport } from './routes/bookings.index'
import { Route as CustomersIdRouteImport } from './routes/customers.$id'
import { Route as CourtsIdRouteImport } from './routes/courts.$id'
import { Route as BookingsIdRouteImport } from './routes/bookings.$id'

const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageRoute = ManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CourtsIndexRoute = CourtsIndexRouteImport.update({
  id: '/courts/',
  path: '/courts/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIndexRoute = BookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIdRoute = CustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CourtsIdRoute = CourtsIdRouteImport.update({
  id: '/courts/$id',
  path: '/courts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIdRoute = BookingsIdRouteImport.update({
  id: '/bookings/$id',
  path: '/bookings/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/finance': typeof FinanceRoute
  '/manage': typeof ManageRoute
  '/more': typeof MoreRoute
  '/notifications': typeof NotificationsRoute
  '/bookings/$id': typeof BookingsIdRoute
  '/courts/$id': typeof CourtsIdRoute
  '/customers/$id': typeof CustomersIdRoute
  '/bookings/': typeof BookingsIndexRoute
  '/courts/': typeof CourtsIndexRoute
  '/customers/': typeof CustomersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/finance': typeof FinanceRoute
  '/manage': typeof ManageRoute
  '/more': typeof MoreRoute
  '/notifications': typeof NotificationsRoute
  '/bookings/$id': typeof BookingsIdRoute
  '/courts/$id': typeof CourtsIdRoute
  '/customers/$id': typeof CustomersIdRoute
  '/bookings': typeof BookingsIndexRoute
  '/courts': typeof CourtsIndexRoute
  '/customers': typeof CustomersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/finance': typeof FinanceRoute
  '/manage': typeof ManageRoute
  '/more': typeof MoreRoute
  '/notifications': typeof NotificationsRoute
  '/bookings/$id': typeof BookingsIdRoute
  '/courts/$id': typeof CourtsIdRoute
  '/customers/$id': typeof CustomersIdRoute
  '/bookings/': typeof BookingsIndexRoute
  '/courts/': typeof CourtsIndexRoute
  '/customers/': typeof CustomersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/finance'
    | '/manage'
    | '/more'
    | '/notifications'
    | '/bookings/$id'
    | '/courts/$id'
    | '/customers/$id'
    | '/bookings/'
    | '/courts/'
    | '/customers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/finance'
    | '/manage'
    | '/more'
    | '/notifications'
    | '/bookings/$id'
    | '/courts/$id'
    | '/customers/$id'
    | '/bookings'
    | '/courts'
    | '/customers'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/finance'
    | '/manage'
    | '/more'
    | '/notifications'
    | '/bookings/$id'
    | '/courts/$id'
    | '/customers/$id'
    | '/bookings/'
    | '/courts/'
    | '/customers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  FinanceRoute: typeof FinanceRoute
  ManageRoute: typeof ManageRoute
  MoreRoute: typeof MoreRoute
  NotificationsRoute: typeof NotificationsRoute
  BookingsIdRoute: typeof BookingsIdRoute
  CourtsIdRoute: typeof CourtsIdRoute
  CustomersIdRoute: typeof CustomersIdRoute
  BookingsIndexRoute: typeof BookingsIndexRoute
  CourtsIndexRoute: typeof CourtsIndexRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courts/': {
      id: '/courts/'
      path: '/courts'
      fullPath: '/courts/'
      preLoaderRoute: typeof CourtsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/': {
      id: '/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof BookingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$id': {
      id: '/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof CustomersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courts/$id': {
      id: '/courts/$id'
      path: '/courts/$id'
      fullPath: '/courts/$id'
      preLoaderRoute: typeof CourtsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/$id': {
      id: '/bookings/$id'
      path: '/bookings/$id'
      fullPath: '/bookings/$id'
      preLoaderRoute: typeof BookingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  FinanceRoute: FinanceRoute,
  ManageRoute: ManageRoute,
  MoreRoute: MoreRoute,
  NotificationsRoute: NotificationsRoute,
  BookingsIdRoute: BookingsIdRoute,
  CourtsIdRoute: CourtsIdRoute,
  CustomersIdRoute: CustomersIdRoute,
  BookingsIndexRoute: BookingsIndexRoute,
  CourtsIndexRoute: CourtsIndexRoute,
  CustomersIndexRoute: CustomersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
