/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MoreRouteImport } from './routes/more'
import { Route as ManageRouteImport } from './routes/manage'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as CourtsRouteImport } from './routes/courts'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomersIdRouteImport } from './routes/customers.$id'
import { Route as CourtsIdRouteImport } from './routes/courts.$id'
import { Route as BookingsIdRouteImport } from './routes/bookings.$id'

const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageRoute = ManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const CourtsRoute = CourtsRouteImport.update({
  id: '/courts',
  path: '/courts',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIdRoute = CustomersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CustomersRoute,
} as any)
const CourtsIdRoute = CourtsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CourtsRoute,
} as any)
const BookingsIdRoute = BookingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BookingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/courts': typeof CourtsRouteWithChildren
  '/customers': typeof CustomersRouteWithChildren
  '/finance': typeof FinanceRoute
  '/manage': typeof ManageRoute
  '/more': typeof MoreRoute
  '/bookings/$id': typeof BookingsIdRoute
  '/courts/$id': typeof CourtsIdRoute
  '/customers/$id': typeof CustomersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/courts': typeof CourtsRouteWithChildren
  '/customers': typeof CustomersRouteWithChildren
  '/finance': typeof FinanceRoute
  '/manage': typeof ManageRoute
  '/more': typeof MoreRoute
  '/bookings/$id': typeof BookingsIdRoute
  '/courts/$id': typeof CourtsIdRoute
  '/customers/$id': typeof CustomersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/courts': typeof CourtsRouteWithChildren
  '/customers': typeof CustomersRouteWithChildren
  '/finance': typeof FinanceRoute
  '/manage': typeof ManageRoute
  '/more': typeof MoreRoute
  '/bookings/$id': typeof BookingsIdRoute
  '/courts/$id': typeof CourtsIdRoute
  '/customers/$id': typeof CustomersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookings'
    | '/calendar'
    | '/courts'
    | '/customers'
    | '/finance'
    | '/manage'
    | '/more'
    | '/bookings/$id'
    | '/courts/$id'
    | '/customers/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookings'
    | '/calendar'
    | '/courts'
    | '/customers'
    | '/finance'
    | '/manage'
    | '/more'
    | '/bookings/$id'
    | '/courts/$id'
    | '/customers/$id'
  id:
    | '__root__'
    | '/'
    | '/bookings'
    | '/calendar'
    | '/courts'
    | '/customers'
    | '/finance'
    | '/manage'
    | '/more'
    | '/bookings/$id'
    | '/courts/$id'
    | '/customers/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingsRoute: typeof BookingsRouteWithChildren
  CalendarRoute: typeof CalendarRoute
  CourtsRoute: typeof CourtsRouteWithChildren
  CustomersRoute: typeof CustomersRouteWithChildren
  FinanceRoute: typeof FinanceRoute
  ManageRoute: typeof ManageRoute
  MoreRoute: typeof MoreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courts': {
      id: '/courts'
      path: '/courts'
      fullPath: '/courts'
      preLoaderRoute: typeof CourtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$id': {
      id: '/customers/$id'
      path: '/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof CustomersIdRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/courts/$id': {
      id: '/courts/$id'
      path: '/$id'
      fullPath: '/courts/$id'
      preLoaderRoute: typeof CourtsIdRouteImport
      parentRoute: typeof CourtsRoute
    }
    '/bookings/$id': {
      id: '/bookings/$id'
      path: '/$id'
      fullPath: '/bookings/$id'
      preLoaderRoute: typeof BookingsIdRouteImport
      parentRoute: typeof BookingsRoute
    }
  }
}

interface BookingsRouteChildren {
  BookingsIdRoute: typeof BookingsIdRoute
}

const BookingsRouteChildren: BookingsRouteChildren = {
  BookingsIdRoute: BookingsIdRoute,
}

const BookingsRouteWithChildren = BookingsRoute._addFileChildren(
  BookingsRouteChildren,
)

interface CourtsRouteChildren {
  CourtsIdRoute: typeof CourtsIdRoute
}

const CourtsRouteChildren: CourtsRouteChildren = {
  CourtsIdRoute: CourtsIdRoute,
}

const CourtsRouteWithChildren =
  CourtsRoute._addFileChildren(CourtsRouteChildren)

interface CustomersRouteChildren {
  CustomersIdRoute: typeof CustomersIdRoute
}

const CustomersRouteChildren: CustomersRouteChildren = {
  CustomersIdRoute: CustomersIdRoute,
}

const CustomersRouteWithChildren = CustomersRoute._addFileChildren(
  CustomersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingsRoute: BookingsRouteWithChildren,
  CalendarRoute: CalendarRoute,
  CourtsRoute: CourtsRouteWithChildren,
  CustomersRoute: CustomersRouteWithChildren,
  FinanceRoute: FinanceRoute,
  ManageRoute: ManageRoute,
  MoreRoute: MoreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
